#!/usr/bin/env python3
"""Generate MEMORY_OVERVIEW.md from memory files."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.memory.memory_manager import get_memory_paths, ensure_memory_layout


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def generate_overview() -> str:
    """Generate MEMORY_OVERVIEW.md content."""
    ensure_memory_layout()
    paths = get_memory_paths()

    # Load long-term index
    index = {}
    if paths.long_term_index.exists():
        try:
            index = json.loads(paths.long_term_index.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass

    # Find working sessions
    working_sessions = list(paths.working.glob("*.json"))[-5:] if paths.working.exists() else []

    # Find short-term files
    short_term_files = sorted(paths.short_term.glob("*.jsonl"))[-7:] if paths.short_term.exists() else []

    # Find long-term docs
    patterns_success = list((paths.long_term / "patterns" / "success").glob("*.md")) if (paths.long_term / "patterns" / "success").exists() else []
    patterns_anti = list((paths.long_term / "patterns" / "anti-patterns").glob("*.md")) if (paths.long_term / "patterns" / "anti-patterns").exists() else []
    evolution = list((paths.long_term / "architecture" / "evolution").glob("*.md")) if (paths.long_term / "architecture" / "evolution").exists() else []
    decisions = list((paths.long_term / "architecture" / "decisions").glob("*.md")) if (paths.long_term / "architecture" / "decisions").exists() else []

    # Build markdown
    lines = [
        "# Memory Overview",
        "",
        f"**Generated:** {_utc_now_iso()}",
        "",
        "## High-Level Summary",
        "",
        "- **Project:** Vektal — AI-powered Shopify multi-supplier platform",
        "- **Status:** v1.0 Final Release COMPLETE",
        "- **Current Focus:** Phase 16 - Agent Context OS",
        "",
        "## Memory Tiers",
        "",
        "### Working Memory (Session Cache)",
        "- **Location:** `.memory/working/`",
        "- **Scope:** Current session (<24 hours)",
        f"- **Recent Sessions:** {len(working_sessions)}",
        "",
    ]

    if working_sessions:
        lines.append("#### Recent Working Files:")
        for s in working_sessions[-3:]:
            lines.append(f"- `.memory/working/{s.name}`")
        lines.append("")

    lines.extend([
        "### Short-Term Memory (Daily Activity)",
        "- **Location:** `.memory/short-term/`",
        "- **Scope:** Last 30 days",
        f"- **Files:** {len(short_term_files)} days of activity",
        "",
    ])

    if short_term_files:
        lines.append("#### Recent Days:")
        for f in short_term_files[-3:]:
            lines.append(f"- `.memory/short-term/{f.name}`")
        lines.append("")

    lines.extend([
        "### Long-Term Memory (Project Knowledge)",
        "- **Location:** `.memory/long-term/`",
        "- **Scope:** Project lifetime",
        "",
        "#### Architecture Decisions:",
    ])
    if decisions:
        for d in decisions:
            lines.append(f"- `.memory/long-term/architecture/decisions/{d.name}`")
    else:
        lines.append("- _No decisions recorded yet_")
    lines.append("")

    lines.append("#### Patterns (Success):")
    if patterns_success:
        for p in patterns_success:
            lines.append(f"- `.memory/long-term/patterns/success/{p.name}`")
    else:
        lines.append("- _No success patterns recorded yet_")
    lines.append("")

    lines.append("#### Patterns (Anti-patterns):")
    if patterns_anti:
        for p in patterns_anti:
            lines.append(f"- `.memory/long-term/patterns/anti-patterns/{p.name}`")
    else:
        lines.append("- _No anti-patterns recorded yet_")
    lines.append("")

    lines.append("#### Evolution:")
    if evolution:
        for e in evolution:
            lines.append(f"- `.memory/long-term/architecture/evolution/{e.name}`")
    else:
        lines.append("- _No evolution docs recorded yet_")
    lines.append("")

    lines.extend([
        "## Quick Links",
        "",
        "- `.planning/STATE.md` — Current project state",
        "- `.planning/ROADMAP.md` — Phase roadmap",
        "- `docs/AGENT_START_HERE.md` — Session primer",
        "- `.memory/long-term/index.json` — Memory index",
        "",
        "---",
        "",
        "_Auto-generated by `scripts/memory/generate_overview.py`_",
    ])

    return "\n".join(lines)


def main() -> int:
    content = generate_overview()
    output_path = REPO_ROOT / "docs" / "MEMORY_OVERVIEW.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"[Memory] Generated: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())