"""AI description generation via OpenRouter API.

This module handles German product description generation using few-shot learning
with similar products from the catalog. Integrates with EmbeddingGenerator for
semantic similarity search.
"""
import os
from typing import List, Optional
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from cachetools import TTLCache
from tenacity import retry, stop_after_attempt, wait_exponential


class AIDescriptionGenerator:
    """Generate German product descriptions via OpenRouter API

    NOTE: This class does NOT load sentence-transformers. Embeddings are
    generated by EmbeddingGenerator (Plan 04) and passed to find_similar_products().
    This prevents duplicate model loading and ensures single source of truth.
    """

    # Cost estimates per 1K products
    COST_ESTIMATES = {
        'google/gemini-flash-1.5': '~$0.03',
        'openai/gpt-4o-mini': '~$0.05',
        'anthropic/claude-3.5-haiku': '~$0.20',
    }

    def __init__(self,
                 api_key: str = None,
                 model: str = "google/gemini-flash-1.5",
                 site_name: str = "Bastelschachtel"):
        """Initialize AI description generator.

        Args:
            api_key: OpenRouter API key (defaults to OPENROUTER_API_KEY env var)
            model: OpenRouter model ID (default: google/gemini-flash-1.5)
            site_name: Store name for context in prompts
        """
        self.api_key = api_key or os.getenv('OPENROUTER_API_KEY')
        if not self.api_key:
            raise ValueError("OpenRouter API key required. Set OPENROUTER_API_KEY env var.")

        self.model = model
        self.site_name = site_name

        # Cache for AI responses (30 day TTL)
        self.cache = TTLCache(maxsize=10000, ttl=2592000)

        # Import requests here to avoid hard dependency
        try:
            import requests
            self.requests = requests
        except ImportError:
            raise ImportError("Install requests: pip install requests")

        # NOTE: No embedding model here - embeddings come from EmbeddingGenerator

    def find_similar_products(self, target_embedding: np.ndarray,
                             catalog_embeddings: np.ndarray,
                             catalog_data: list,
                             top_k: int = 3) -> list:
        """Find similar products for few-shot examples.

        Args:
            target_embedding: Pre-computed 768-dim embedding for target product
                             (from EmbeddingGenerator)
            catalog_embeddings: Pre-computed embeddings for catalog products
            catalog_data: List of product dicts corresponding to embeddings
            top_k: Number of similar products to return

        Returns:
            List of top_k most similar products from catalog
        """
        # Step 1: Compute cosine similarity between target and all catalog embeddings
        # cosine_similarity returns shape (1, n_catalog), so [0] gets the 1D array
        similarities = cosine_similarity([target_embedding], catalog_embeddings)[0]

        # Step 2: Get indices of top_k highest similarity scores
        # np.argsort returns indices in ascending order, so we take last k and reverse
        top_indices = np.argsort(similarities)[-top_k:][::-1]

        # Step 3: Return the corresponding catalog products
        return [catalog_data[i] for i in top_indices]

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=30))
    def generate_description(self, product: dict, examples: list) -> str:
        """Generate German description using OpenRouter.

        Args:
            product: Product dict with title, vendor, category, etc.
            examples: List of similar products with good descriptions

        Returns:
            AI-generated German product description
        """
        # Check cache first
        cache_key = (product['title'], product.get('vendor'), product.get('category'))
        if cache_key in self.cache:
            return self.cache[cache_key]

        # Build examples text
        examples_text = "\n\n".join([
            f"Beispiel {i+1}:\nTitel: {ex['title']}\nKategorie: {ex.get('category', '')}\nBeschreibung: {ex['description'][:200]}"
            for i, ex in enumerate(examples[:3])
        ])

        # Build prompt with German system message
        system_prompt = f"""Du bist ein erfahrener E-Commerce Texter für {self.site_name}, einen österreichischen Online-Shop für Kunsthandwerk-Bedarf (Decoupage, Resin, Mixed Media, Textilgestaltung)."""

        user_prompt = f"""Schreibe eine überzeugende, informative Produktbeschreibung für dieses Produkt:

PRODUKT:
Titel: {product['title']}
Marke: {product.get('vendor', 'Pentart')}
Kategorie: {product.get('category', 'Bastelbedarf')}
Farbe: {product.get('color', 'Nicht angegeben')}
Größe: {product.get('size', '')}

Hier sind 3 ähnliche Produkte mit guten Beschreibungen als Referenz:

{examples_text}

AUFGABE:
Schreibe eine deutsche Produktbeschreibung (maximal 200 Zeichen, 2-3 kurze Sätze):
1. Erkläre wofür das Produkt hauptsächlich verwendet wird (Decoupage, Resin, Schmuck, etc.)
2. Erwähne wichtige Eigenschaften (waschbar, wasserfest, etc. falls bekannt)
3. Nutze einen professionellen, aber ansprechenden Ton
4. Halte es faktenbasiert - keine Übertreibungen
5. Wenn möglich, erwähne die Verarbeitung oder Anwendung

WICHTIG: Antworte NUR mit der Produktbeschreibung, keine Einleitung, keine Anführungszeichen."""

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://bastelschachtel.at",
            "X-Title": self.site_name
        }

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.3,  # Low for consistency
            "max_tokens": 300
        }

        # Call OpenRouter API
        response = self.requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            json=payload,
            headers=headers,
            timeout=30
        )
        response.raise_for_status()

        result = response.json()
        description = result['choices'][0]['message']['content'].strip()

        # Clean up response
        description = description.replace('"', '').replace("'", "")
        if description.startswith('Produktbeschreibung:'):
            description = description[20:].strip()
        if description.startswith('Beschreibung:'):
            description = description[13:].strip()

        # Cache and return result
        self.cache[cache_key] = description
        return description

    def generate_batch(self, products: list,
                      catalog_embeddings: np.ndarray = None,
                      catalog_data: list = None,
                      max_products: int = None) -> list:
        """Generate descriptions for multiple products.

        Args:
            products: Products to generate descriptions for
            catalog_embeddings: Pre-computed embeddings for finding similar products
            catalog_data: Catalog products for few-shot examples
            max_products: Limit generation count

        Returns:
            List of (product, description) tuples
        """
        if max_products:
            products = products[:max_products]

        results = []
        for product in products:
            # Find similar products if embeddings provided
            examples = []
            if catalog_embeddings is not None and catalog_data is not None:
                # Get target embedding from product (assumes it's pre-computed)
                target_embedding = product.get('embedding')
                if target_embedding is not None:
                    examples = self.find_similar_products(
                        target_embedding,
                        catalog_embeddings,
                        catalog_data,
                        top_k=3
                    )

            # Generate description
            if len(examples) >= 2:  # Need at least 2 examples
                description = self.generate_description(product, examples)
                results.append((product, description))
            else:
                # Not enough similar products, skip for now
                results.append((product, None))

        return results
