"""Patch agent models in Letta to real OpenRouter model IDs.

model-rationale.md v2.0 used fictional 2026 model names.
This script corrects them to verified OpenRouter IDs (2025-03-09).

Usage:
    python scripts/letta/patch_agent_models.py           # patch all
    python scripts/letta/patch_agent_models.py commander # patch single
"""
import os, sys, json, requests, argparse
from pathlib import Path
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")

BASE    = os.getenv("LETTA_BASE_URL", "https://api.letta.com")
KEY     = os.getenv("LETTA_API_KEY", "")
HEADERS = {"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"}

REGISTRY = json.loads((ROOT / ".letta" / "agent-registry.json").read_text(encoding="utf-8"))

# Verified real OpenRouter model IDs (2025-03-09)
# Sources:
#   grok-3:          openrouter.ai/compare/x-ai/grok-3/...
#   claude-opus-4-6: docs.claude.com (Anthropic API ID — dash not dot)
#   kimi-k2.5:       openrouter.ai/moonshotai/kimi-k2.5 (released 2026-01-27)
#   deepseek-v3.2:   openrouter.ai/deepseek/deepseek-v3.2/api
#   glm-4.6:         openrouter.ai/compare/.../z-ai/glm-4.6
#   gemini-2.5-flash-lite: openrouter.ai (confirmed in models list)
CORRECTED_MODELS = {
    "commander":          "lc-openrouter/x-ai/grok-3",
    "watson":             "lc-openrouter/anthropic/claude-opus-4-6",
    "bundle":             "lc-openrouter/google/gemini-2.5-flash",
    "engineering-lead":   "lc-openrouter/openai/gpt-4o",
    "design-lead":        "lc-openrouter/qwen/qwen-2.5-coder-32b-instruct",
    "forensic-lead":      "lc-openrouter/deepseek/deepseek-v3.2",
    "infrastructure-lead":"lc-openrouter/z-ai/glm-4.6",
    "project-lead":       "lc-openrouter/google/gemini-2.5-flash",
    "task-observer":      "lc-openrouter/google/gemini-2.5-flash-lite",
    "validator":          "lc-openrouter/openai/gpt-4o-mini",
}


def patch_agent(name: str) -> bool:
    agent = REGISTRY.get(name)
    if not agent:
        print(f"  {name}: NOT IN REGISTRY")
        return False
    agent_id = agent["id"]
    model    = CORRECTED_MODELS[name]

    r = requests.patch(
        f"{BASE}/v1/agents/{agent_id}",
        headers=HEADERS,
        json={"model": model},
        timeout=15,
    )
    if r.ok:
        print(f"  {name:<20} → {model}  GREEN")
        return True
    else:
        print(f"  {name:<20} → {model}  RED ({r.status_code}: {r.text[:120]})")
        return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("agents", nargs="*", help="Agent name(s) to patch. Default: all.")
    args = parser.parse_args()

    targets = args.agents if args.agents else list(CORRECTED_MODELS.keys())
    print(f"Patching {len(targets)} agent(s)...\n")

    ok = sum(patch_agent(n) for n in targets)
    print(f"\n{ok}/{len(targets)} patched successfully.")

    if ok == len(targets):
        # Update registry with new model names
        for name in targets:
            if name in REGISTRY:
                REGISTRY[name]["model"] = CORRECTED_MODELS[name]
        REGISTRY["_note"] = (
            "Generated by scripts/letta/register_agents.py. "
            "Models corrected 2025-03-09 by patch_agent_models.py to real OpenRouter IDs."
        )
        (ROOT / ".letta" / "agent-registry.json").write_text(
            json.dumps(REGISTRY, indent=2), encoding="utf-8"
        )
        print("Registry updated.")
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
