"""p17_01_product_data_contract_v2

Revision ID: 13bac515cdf9
Revises: 783334eae760
Create Date: 2026-03-06 22:14:42.154842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bac515cdf9'
down_revision = '783334eae760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_completeness_score'), ['completeness_score'], unique=False)

    with op.batch_alter_table('shopify_stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_full_ingest_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_shopify_cursor', sa.String(length=255), nullable=True))

    # JobType Enum update is handled by the application layer, but we ensure the constraint is updated if needed.
    # The Index uq_jobs_active_ingest_per_store was already updated in the model and will be picked up on next full sync if not already.
    # Since we are using PostgreSQL, we might need to manually update the Enum type if it's strictly enforced.
    op.execute("ALTER TYPE job_type ADD VALUE IF NOT EXISTS 'ingest_shopify'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopify_stores', schema=None) as batch_op:
        batch_op.drop_column('last_shopify_cursor')
        batch_op.drop_column('last_full_ingest_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_completeness_score'))
        batch_op.drop_column('completeness_score')

    # Note: Removing a value from a Postgres Enum is not straightforward and often not recommended.
    # ### end Alembic commands ###
