"""p17_01_product_data_contract

Revision ID: 783334eae760
Revises: p15_02_remedy_template_cache
Create Date: 2026-03-06 21:45:51.154842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '783334eae760'
down_revision = 'p15_02_remedy_template_cache'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sandbox_run_id', sa.String(length=36), nullable=True),
    sa.Column('blast_radius_files', sa.Integer(), nullable=True),
    sa.Column('blast_radius_loc', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_approvals'))
    )
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.create_index('idx_pending_approvals_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_pending_approvals_priority', ['priority', 'created_at'], unique=False)
        batch_op.create_index('idx_pending_approvals_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approvals_approval_id'), ['approval_id'], unique=True)

    with op.batch_alter_table('assistant_delegation_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_assistant_delegation_events_request_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_assistant_delegation_events_request_id'))
        batch_op.create_index(batch_op.f('ix_assistant_delegation_events_request_id'), ['request_id'], unique=True)

    with op.batch_alter_table('assistant_execution_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_execution_ledger_correlation_id'))
        batch_op.drop_constraint(batch_op.f('uq_assistant_execution_ledger_idempotency_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_assistant_execution_ledger_idempotency_key'))
        batch_op.create_index(batch_op.f('ix_assistant_execution_ledger_idempotency_key'), ['idempotency_key'], unique=True)

    with op.batch_alter_table('assistant_tool_registry', schema=None) as batch_op:
        batch_op.alter_column('schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_assistant_tool_registry_tool_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_assistant_tool_registry_tool_id'))
        batch_op.create_index(batch_op.f('ix_assistant_tool_registry_tool_id'), ['tool_id'], unique=True)

    with op.batch_alter_table('audit_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_checkpoints_checkpoint'))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('total_items',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('processed_items',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('successful_items',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('failed_items',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collections_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metafields_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('price_per_unit_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('price_per_unit_unit', sa.String(length=50), nullable=True))

    with op.batch_alter_table('recovery_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_logs_created_by_user_id'), ['created_by_user_id'], unique=False)

    with op.batch_alter_table('remedy_template_cache', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_remedy_template_cache_template_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_remedy_template_cache_template_id'))
        batch_op.create_index(batch_op.f('ix_remedy_template_cache_template_id'), ['template_id'], unique=True)

    with op.batch_alter_table('resolution_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolution_items_supplier_code'), ['supplier_code'], unique=False)

    with op.batch_alter_table('resolution_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolution_rules_created_by_user_id'), ['created_by_user_id'], unique=False)

    with op.batch_alter_table('resolution_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_resolution_snapshot_item', ['item_id'], unique=False)

    with op.batch_alter_table('sandbox_runs', schema=None) as batch_op:
        batch_op.alter_column('verdict',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_sandbox_runs_run_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_sandbox_runs_run_id'))
        batch_op.create_index(batch_op.f('ix_sandbox_runs_run_id'), ['run_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_stripe_subscription_id'), ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_stripe_subscription_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)

    with op.batch_alter_table('sandbox_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_runs_run_id'))
        batch_op.create_index(batch_op.f('ix_sandbox_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_sandbox_runs_run_id'), ['run_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('verdict',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('resolution_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_resolution_snapshot_item')

    with op.batch_alter_table('resolution_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolution_rules_created_by_user_id'))

    with op.batch_alter_table('resolution_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolution_items_supplier_code'))

    with op.batch_alter_table('remedy_template_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remedy_template_cache_template_id'))
        batch_op.create_index(batch_op.f('ix_remedy_template_cache_template_id'), ['template_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_remedy_template_cache_template_id'), ['template_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('recovery_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_logs_created_by_user_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price_per_unit_unit')
        batch_op.drop_column('price_per_unit_value')
        batch_op.drop_column('metafields_json')
        batch_op.drop_column('collections_json')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('failed_items',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('successful_items',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('processed_items',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_items',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_checkpoints_checkpoint'), ['checkpoint'], unique=False)

    with op.batch_alter_table('assistant_tool_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_tool_registry_tool_id'))
        batch_op.create_index(batch_op.f('ix_assistant_tool_registry_tool_id'), ['tool_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_assistant_tool_registry_tool_id'), ['tool_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('schema_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('assistant_execution_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_execution_ledger_idempotency_key'))
        batch_op.create_index(batch_op.f('ix_assistant_execution_ledger_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_assistant_execution_ledger_idempotency_key'), ['idempotency_key'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_assistant_execution_ledger_correlation_id'), ['correlation_id'], unique=False)

    with op.batch_alter_table('assistant_delegation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_delegation_events_request_id'))
        batch_op.create_index(batch_op.f('ix_assistant_delegation_events_request_id'), ['request_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_assistant_delegation_events_request_id'), ['request_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_approvals_approval_id'))
        batch_op.drop_index('idx_pending_approvals_status')
        batch_op.drop_index('idx_pending_approvals_priority')
        batch_op.drop_index('idx_pending_approvals_expires')

    op.drop_table('pending_approvals')
    # ### end Alembic commands ###
