"""Initial schema: users, stores, vendors, products, jobs

Revision ID: e6eec7532bd6
Revises: 
Create Date: 2026-02-08 21:34:01.139095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6eec7532bd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='user_tier', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tier'), ['tier'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.Enum('PRODUCT_SYNC', 'PRODUCT_ENRICH', 'IMAGE_PROCESS', 'CATALOG_IMPORT', 'VENDOR_SCRAPE', name='job_type', create_constraint=True), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status', create_constraint=True), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('successful_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_celery_task_id'), ['celery_task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('shopify_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopify_stores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopify_stores'))
    )
    with op.batch_alter_table('shopify_stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_stores_shop_domain'), ['shop_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_shopify_stores_user_id'), ['user_id'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('config_file', sa.String(length=255), nullable=True),
    sa.Column('catalog_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catalog_item_count', sa.Integer(), nullable=True),
    sa.Column('catalog_source', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('user_id', 'code', name='uq_vendor_user_code')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.BigInteger(), nullable=True),
    sa.Column('shopify_variant_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('country_of_origin', sa.String(length=2), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['shopify_stores.id'], name=op.f('fk_products_store_id_shopify_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_shopify_product_id'), ['shopify_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_shopify_variant_id'), ['shopify_variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_store_id'), ['store_id'], unique=False)

    op.create_table('shopify_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('credential_name', sa.String(length=255), nullable=True),
    sa.Column('credential_value_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['shopify_stores.id'], name=op.f('fk_shopify_credentials_store_id_shopify_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopify_credentials'))
    )
    with op.batch_alter_table('shopify_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_credentials_credential_type'), ['credential_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopify_credentials_store_id'), ['store_id'], unique=False)

    op.create_table('vendor_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('vendor_product_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_catalog_items_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_catalog_items'))
    )
    with op.batch_alter_table('vendor_catalog_items', schema=None) as batch_op:
        batch_op.create_index('ix_vendor_catalog_barcode', ['vendor_id', 'barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_catalog_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_catalog_items_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_catalog_items_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index('ix_vendor_catalog_lookup', ['vendor_id', 'sku', 'barcode'], unique=False)
        batch_op.create_index('ix_vendor_catalog_sku', ['vendor_id', 'sku'], unique=False)

    op.create_table('job_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_sku', sa.String(length=255), nullable=True),
    sa.Column('item_barcode', sa.String(length=255), nullable=True),
    sa.Column('item_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_results_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_job_results_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_results'))
    )
    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_results_item_sku'), ['item_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_results_job_id'), ['job_id'], unique=False)

    op.create_table('product_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=512), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('materials', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('dimensions', sa.String(length=255), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_issues', sa.JSON(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('title_embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('description_embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('generation_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_enrichments_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_enrichments'))
    )
    with op.batch_alter_table('product_enrichments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_enrichments_product_id'), ['product_id'], unique=True)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('src_url', sa.String(length=1024), nullable=False),
    sa.Column('alt_text', sa.String(length=512), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('vision_analyzed', sa.Boolean(), nullable=True),
    sa.Column('vision_labels', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('vision_colors', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('vision_text', sa.Text(), nullable=True),
    sa.Column('vision_quality', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('product_enrichments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_enrichments_product_id'))

    op.drop_table('product_enrichments')
    with op.batch_alter_table('job_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_results_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_results_item_sku'))

    op.drop_table('job_results')
    with op.batch_alter_table('vendor_catalog_items', schema=None) as batch_op:
        batch_op.drop_index('ix_vendor_catalog_sku')
        batch_op.drop_index('ix_vendor_catalog_lookup')
        batch_op.drop_index(batch_op.f('ix_vendor_catalog_items_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_catalog_items_sku'))
        batch_op.drop_index(batch_op.f('ix_vendor_catalog_items_barcode'))
        batch_op.drop_index('ix_vendor_catalog_barcode')

    op.drop_table('vendor_catalog_items')
    with op.batch_alter_table('shopify_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_credentials_store_id'))
        batch_op.drop_index(batch_op.f('ix_shopify_credentials_credential_type'))

    op.drop_table('shopify_credentials')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_store_id'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_shopify_variant_id'))
        batch_op.drop_index(batch_op.f('ix_products_shopify_product_id'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_user_id'))
        batch_op.drop_index('ix_vendor_user_active')

    op.drop_table('vendors')
    with op.batch_alter_table('shopify_stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_stores_user_id'))
        batch_op.drop_index(batch_op.f('ix_shopify_stores_shop_domain'))

    op.drop_table('shopify_stores')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_celery_task_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tier'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
